### ISSUE TITLE
Stop logging when the MOC does not have changes

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/RZVinyl#61]
My app logs are full of this:

> Managed object context <NSManagedObjectContext: 0x1146acad0> does not have changes, not saving

It doesn't seem that useful. Consider silencing it, or making it configurable.

**Comment by mr-fixit** [comment]
+1

**Comment by jwatson** [comment]
I recommend making it configurable. It is occasionally useful when debugging, but is otherwise too noisy.

**Comment by bsmith11** [comment]
It could be nice to go a step further and make all of the logging configurable

**Comment by ZevEisenberg** [comment]
![](https://imgs.xkcd.com/comics/the_general_problem.png)

**Comment by mr-fixit** [comment]
There’s a video gag like this, of an engineer changing a lightbulb.  He’s continually distracted by yet-another-broken-thing.

**Comment by mr-fixit** [comment]
I would have had this done sooner, but I had to vacuum the whole house, and that took some time because I stopped partway through to fix the short in the power cord.  I almost took apart my butane soldering iron to try and figure out why its pizo-electric sparker wasn't working, but I held myself back.  (the previous is 100% All True™)

**Comment by ZevEisenberg** [comment]
If you give a 🐭 a 🍪…
